### ISSUE TITLE
miniproject1 for Victor Hazlewood

### ISSUE THREAD

**Issue by uxvictor** [AndersonWalsh/MiniProject1#1]
@AndersonWalsh I have converted the following PDF papers on omics tools to text and will compare them to see what is different between the two. 

Misra, Biswapriya B., Carl Langefeld, Michael Olivier, and Laura A. Cox. "Integrated omics: tools, advances and future approaches." Journal of molecular endocrinology 62, no. 1 (2019): R21-R45.

Misra, Biswapriya B. "New software tools, databases, and resources in metabolomics: Updates from 2020." Metabolomics 17, no. 5 (2021): 1-24.

**Comment by AndersonWalsh** [comment]
Hey @uxvictor. I had never heard of omics until looking it up after reading your issue. So it's the study of biological fields ending in "omics", but in this context we're specifically discussing software tools to interact with omics data? Sounds like  interesting work, I'm looking forward to seeing what you come up with.

**Comment by uxvictor** [comment]
Yes, that is a growing community at UTK.  There are omics people everywhere now - UTIA, several UTK depts (microbiology, biology, chemistry, and EECS).  I am trying to get up to speed on that communities software tools.  That author has written some good surveys of tools
