### ISSUE TITLE
writing a no-op issue

### ISSUE THREAD

**Issue by uxvictor** [AndersonWalsh/MiniProject1#2]
How is your MiniProject coming.   If you have been working on it, push it to your fork and I'll write a couple of issues. I think that was one of the things we were supposed to do also.

**Comment by AndersonWalsh** [comment]
Hey @uxvictor, sorry for not having pushed any changes sooner. There's some content for you to look at now. I decided to compare works of science fiction between multiple authors. Let me know what you think.
